### ISSUE TITLE
RPG Awesome Icons do not change color

### ISSUE THREAD

**Issue by namtrah** [matthewturk/obsidian-additional-icons#2]
I am using this and noticed that when I use a RPG Awesome icon like I would a Lucide icon that it doesn't change color. I have not tried the other two. But could it be that you force a BLACK line? Could you make it so that I can change the color through CSS (like I do with Lucide Icons?)

**Comment by namtrah** [comment]
Here is an example:
```css
  .theme-dark {
    --nav-icon-color: var(--nord5); /*Choose a color*/
  }
  .theme-light {
    --nav-icon-color: var(--nord2); /*Choose a color*/ 
  }

  .nav-file-title .nav-file-title-content,
  .nav-file-title:hover .nav-file-title-content
  .nav-folder-title .nav-folder-title-content,
  .nav-folder-title:hover .nav-folder-title-content {
    color: var(--text-bold);
    font-weight: bold;
  }
  
  /* Icons */
  .nav-files-container .nav-file-title .nav-folder-title .lucide-icon {
    display: flex;
    margin-right: var(--size-2-3);
  }

  .nav-files-container .ra-crown-of-thorns { /* This does not allow a color change */
    stroke: var(--nav-icon-color);
  }

  .nav-files-container .lucide-archive { /* This does allow a color change */
    stroke: var(--nav-icon-color);
  }
```
